config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'people#index'

  resources :people, only: [:create, :new, :index, :show]
  resources :checkins, only: [:create, :new]
  resources :events, only: [:create, :new, :index, :show,]

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  belongs_to :person
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope { order(created_at: :asc) }

  has_many :league_event_joins
  has_many :leagues, through: :league_event_joins
  has_many :checkins
  has_many :people, -> { distinct }, through: :checkins
end

app/models/league.rb
class League < ActiveRecord::Base

  has_many :league_person_joins
  has_many :people, through: :league_person_joins
  has_many :league_event_joins
  has_many :events, through: :league_event_joins
end

app/models/league_event_join.rb
class LeagueEventJoin < ActiveRecord::Base
   belongs_to :league
   belongs_to :event
end

app/models/league_person_join.rb
class LeaguePersonJoin < ActiveRecord::Base
  belongs_to :league
  belongs_to :person
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :user_location_joins
  has_many :users, through: :user_location_joins
end

app/models/person.rb
class Person < ActiveRecord::Base

  has_many :league_person_joins
  has_many :people, through: :league_person_joins
  has_many :checkins
  has_many :user_person_joins
  has_many :users, through: :user_person_joins

  def up_by(event=nil)
    return attributes['up_by'] unless event
    checkins_from_event = event.checkins.where(person: self).order(:created_at)
    first_checkin = checkins_from_event.first
    last_checkin = checkins_from_event.last
    last_checkin == first_checkin ? nil : last_checkin.weight - first_checkin.weight
    puts "#{up_by}"
  end

  def percentage_change
    return unless up_by
    @percentage_change ||= starting_weight ?  up_by.to_f / starting_weight * 100 : nil
  end

  def checkin_diffs
    grouped = checkins.includes(:event).order('events.created_at').group_by(&:event)
    event_diffs = {}
    grouped.each_pair do |event, event_checkins|
      diffs = event_checkins.sort_by(&:created_at).map(&:delta).compact
      event_diffs[event.try(:name)] = diffs.map { |d| '%.2f' % d }
    end
    event_diffs
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :user_person_joins
  has_many :people, through: :user_person_joins
  has_many :user_location_joins
  has_many :locations, through: :user_location_joins
end

app/models/user_location_join.rb
class UserLocationJoin < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/models/user_person_join.rb
class UserPersonJoin < ActiveRecord::Base
  belongs_to :user
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  def create
    person = Person.find(checkin_params[:person_id])
    @checkin = CreateCheckin.call(person, Event.last, checkin_params[:weight].to_f, current_user)
    redirect_to people_path
  rescue
    flash[:error] = "Please fill out all fields"
    redirect_to new_checkin_path
  end

  def new
    @people = Person.all.order(:name)
  end

  private
  def checkin_params
    params.require(:checkin).permit(:weight, :person_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.order(:id)
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.create(event_params)
    redirect_to people_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :tagline)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def create
    @location = Location.create(location_params)
    redirect_to new_checkin_path
  end

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  private
  def location_params
    params.required(:location).permit([:name])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def create
    @person = Person.create(person_params)
    CreateCheckin.call(@person, Event.last, checkin_params[:weight].to_f, current_user)
    redirect_to people_path
  end

  def index
    @event = Event.last
    unless @event
      redirect_to new_event_path
    end
  end

  def show
    @person = Person.find(params[:id])
  end

  private
  def person_params
    params.required(:person).permit([:name])
  end

  def checkin_params
    params.required(:person).permit([:weight])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkins/new.haml
%h1{class: 'text-center'} New Checkin
%div

- flash.each do |key, value|
  .alert{ :class => "alert-#{key}" }
    %button.close{ :data => { :dismiss => "alert" } } x
    %strong
      = value
%div
  .input-group
    = form_for :checkin, url: checkins_path do |f|
      - options = ['SELECT YOUR NAME'] + @people.map { |person| [person.name, person.id] }
      = f.select :person_id, options_for_select(options, disabled: ['-'*20]), class: 'input-block-level'
      %br
      = link_to('Not Listed?', new_person_path, class: 'btn btn-default btn-block') unless ENV['QUIET_MODE']
      %p
      = f.label :weight
      %br
      = f.text_field :weight, { autocomplete: :off, class: "form-control" }
      = f.submit class: "btn btn-primary text-uppercase btn-block", value: 'SAVE >'

%h3
  %a= link_to('< Back', people_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/events/index.haml
%h1{class: 'text-center'}= "List of events:"
%div{class: 'table-container'}
  %table{border: 0, class: 'table table-condensed borderless'}
    %tr
      %th{class: 'ordinal'}
      %th{class: 'text-left person-name'} NAME
    - @events.each_with_index do |event, index|
      / TODO: add winner here
      %tr
        %td{class: 'ordinal'}= index
        %td{class: "text-left weight"}=link_to(event.name, event_path(event.id))

%br
%br
%br
%br
%br
= link_to('CURRENT EVENT', people_path)

app/views/events/new.haml
%h1{class: 'text-center'} Please create a New Event
%div

- flash.each do |key, value|
  .alert{ :class => "alert-#{key}" }
    %button.close{ :data => { :dismiss => "alert" } } x
    %strong
      = value
%div
  .input-group
    = form_for :event, url: events_path do |f|
      %p
      = f.label :name
      %br
      = f.text_field :name, { autocomplete: :off, class: "form-control" }
      %p
      = f.label :tagline
      %br
      = f.text_field :tagline, { autocomplete: :off, class: "form-control" }
      = f.submit class: "btn btn-primary text-uppercase btn-block", value: 'SAVE >'

%h3
  %a= link_to('< Back', people_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/events/show.haml
%h2
  #{@event.name}
- @event.people.each_with_index do |person, index|
  %table
    %tr
      %td{class: 'ordinal'}= index
      %td{class: "text-left"}=link_to(person.name, person_path(person.id))
      %td{class: "text-left weight"}=person.up_by(@event)
  %br
%br
%br
%br
%br
%br
%h3
  %a= link_to('< Back', people_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
  <title>EAT TO COMPETE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=yes">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> -->
</head>
<body>
  <div class="container text-uppercase">
    <%= yield %>
  </div>
</body>
</html>

app/views/locations/new.haml
%h1 New Location
.input-group
  = form_for :location, url: locations_path do |f|
    %p
    = f.label :name
    %br
    = f.text_field :name, { class: "form-control" }
    %p
    = f.submit class: "btn btn-primary text-uppercase btn-block", value: 'SAVE >'
%h3
  %a= link_to('< Back', new_checkin_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/locations/show.haml
%h2
  #{@location.name}
  %a= link_to('< Back', checkins_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/people/index.haml
%h1{class: 'text-center'}= "WEIGH-IN #{@event.name}"
%h2{class: 'text-center'}= @event.tagline
%div{class: 'table-container'}
  %table{border: 0, class: 'table table-condensed borderless'}
    %tr
      %th{class: 'ordinal'}
      %th{class: 'text-left person-name'} NAME
      %th{:'data-field' => 'up_by', :'data-sortable' => 'true', class: 'text-right weight'} UP BY
    - previous_score = nil
    - index = 0
    - people_with_current_rank = 1
    - @event.people.sort_by{|p| p.up_by || -1000 }.reverse.each do |person|
      - up_by = person.try(:up_by)
      - positive = up_by.to_f > 0 ? 'positive' : 'negative'
      %tr
        - percentage_change = person.try(:percentage_change)
        - if up_by.to_f == previous_score.to_f
          - people_with_current_rank += 1
        - else
          - index += people_with_current_rank
          - people_with_current_rank = 1
        - previous_score = up_by
        %td{class: 'ordinal'}= up_by ? index : nil
        %td{class: 'person-name'}= link_to(person.name.upcase, person_path(person))
        - percent_text = up_by && percentage_change ? "(#{percentage_change.round(2)}%)" : ""
        %td{class: "#{positive} text-right weight"}= "#{up_by.try(:round, 3)} #{percent_text}"

%br
%br
%br
%br
%br
= link_to('OTHER EVENTS', events_path)
= link_to('CHECK IN', new_checkin_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom button-link') unless ENV['QUIET_MODE']

app/views/people/new.haml
%h1 New Person
.input-group
  = form_for :person, url: people_path do |f|
    %p
    = f.label :name
    %br
    = f.text_field :name, { class: "form-control" }
    %p
    = f.label :weight
    %br
    = f.text_field :weight, { autocomplete: :off, class: "form-control" }
    %br
    = f.submit class: "btn btn-primary text-uppercase btn-block", value: 'SAVE >'
%h3
  %a= link_to('< Back', new_checkin_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')

app/views/people/show.haml
%h2
  #{@person.name}
- @person.try(:checkin_diffs).each_pair do |event, diffs|
  %table
    %th= event
    -diffs.each do |diff|
      - classname = diff.to_f > 0 ? 'positive' : 'negative'
      %tr
        %td{class: classname} #{diff.to_f}
  %br
%br
%br
%br
%br
%br
%h3
  %a= link_to('< Back', people_path, class: 'btn btn-default btn-block navbar navbar-fixed-bottom')